name: Testing Ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  uni_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-verion:"3.11"
            
      - name: Run unit tests
        run: |
          python -m pip install --upgrade pip
          pip install uv 
          uv sync --dev
          uv run pytest -v -s || #Fail the job if any tests fail 
